eureka:
  client:
    serviceUrl:
      defaultZone: http://${host.name}:${host.port}/eureka/

server:
  port: 7004

spring:
  application:
    name: service-feign1

#配置断路器的仪表盘路径
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

host:
  name: localhost
  port: 7000


